added clone factory
PrimeDAO/contracts pull request #43
Opened 2021-03-03 16:10 UTC by BritikovKI

Added clone factory to the clone factory.

2021-03-04 11:31 UTC, kinspotting requested changes
needs minor changes

2021-03-04 11:31 UTC, kinspotting commented on contracts/schemes/FarmFactory.sol
> +	StakingRewards public father;
pls change `father` to `parent`

2021-03-04 11:31 UTC, kinspotting commented on contracts/schemes/FarmFactory.sol
> +		//		TODO: there is a possibility to make it more flexible, and to send father address as a constructor parameter
let's do it on construction

2021-03-06 20:57 UTC, BritikovKI commented on contracts/schemes/FarmFactory.sol
> +	StakingRewards public father;
Done

2021-03-06 20:57 UTC, BritikovKI commented on contracts/schemes/FarmFactory.sol
> +		//		TODO: there is a possibility to make it more flexible, and to send father address as a constructor parameter
Done

2021-03-08 13:35 UTC, kinspotting approved these changes
lgtm

2021-03-08 13:36 UTC, merged