Tests fixed + I noticed that I must've messed up a contract somewhere
PrimeDAO/contracts pull request #46
Opened 2021-03-12 08:24 UTC by BritikovKI

2021-03-15 11:07 UTC, kinspotting approved these changes
lgtm

2021-03-15 11:07 UTC, kinspotting commented on test/staking-rewards.js
> +                    // expect((await setup.tokens.primeToken.balanceOf(accounts[1])).toString()).to.equal('0');
delete comment

2021-03-15 11:07 UTC, kinspotting commented on test/staking-rewards.js
> +                    // let rewardEarned = Number(await setup.incentives.stakingRewards.earned(accounts[1]));
delete comment

2021-03-15 11:07 UTC, kinspotting commented on test/staking-rewards.js
> +                    // let balance = Number(await setup.tokens.primeToken.balanceOf(accounts[1]));
delete comment

2021-03-15 11:09 UTC, kinspotting requested changes
needs minor changes

2021-03-18 12:54 UTC, BritikovKI commented on test/staking-rewards.js
> +                    // expect((await setup.tokens.primeToken.balanceOf(accounts[1])).toString()).to.equal('0');
Done

2021-03-18 12:54 UTC, BritikovKI commented on test/staking-rewards.js
> +                    // let rewardEarned = Number(await setup.incentives.stakingRewards.earned(accounts[1]));
Done

2021-03-18 12:54 UTC, BritikovKI commented on test/staking-rewards.js
> +                    // let balance = Number(await setup.tokens.primeToken.balanceOf(accounts[1]));
Done

2021-03-18 12:57 UTC, kinspotting approved these changes

2021-03-18 13:00 UTC, merged