add metadata hash
PrimeDAO/contracts pull request #66
Opened 2021-04-12 12:20 UTC by kinspotting

Closes https://github.com/PrimeDAO/contracts/issues/64

2021-04-12 19:02 UTC, dkent600 requested changes

2021-04-12 19:02 UTC, dkent600 commented on contracts/seed/Seed.sol
> +    event MetadataUpdated(bytes32 metadata);
Can `metadata` please be indexed?

2021-04-12 19:26 UTC, kinspotting commented on contracts/seed/Seed.sol
> +    function updateMetadata(bytes32 _metadata) public protected {
why would we want to update metadata of an inactive seed?

2021-04-12 19:31 UTC, dkent600 commented on contracts/seed/Seed.sol
> +    function updateMetadata(bytes32 _metadata) public protected {
Just because it is inactive doesn't mean I might not want to change the metadata about it.

2021-04-12 19:32 UTC, dkent600 commented on contracts/seed/Seed.sol
> +    function updateMetadata(bytes32 _metadata) public protected {
I might want to change the social urls, or add information about how fantastically successful it was :-)

2021-04-13 13:02 UTC, dkent600 requested changes

2021-04-13 13:02 UTC, dkent600 commented on contracts/seed/Seed.sol
> +        require(initialized != true || msg.sender == admin , "Seed: caller should be admin or beneficiary");
the msg is wrong

2021-04-13 13:06 UTC, dkent600 approved these changes

2021-04-13 13:26 UTC, merged