94 deploy to kovan
PrimeDAO/contracts pull request #96
Opened 2021-04-23 13:10 UTC by kinspotting

Closes https://github.com/PrimeDAO/contracts/issues/94

2021-04-26 13:36 UTC, dkent600 approved these changes

2021-04-26 13:37 UTC, BritikovKI requested changes

2021-04-26 13:37 UTC, BritikovKI commented on config.json
> +"crPool1":{
Shouldn't we have 3 polls according to the issue?

2021-04-26 13:37 UTC, BritikovKI commented on farmconfig.json
> +          "crpPool": "0x0BdAF6D38150B0Aed813634b1a1239E690e506f2",
Maybe we should add issue on validation of this SCs?

2021-04-26 13:37 UTC, BritikovKI commented on test/staking-rewards.js
> -                await setup.incentives.stakingRewards.initialize(_name, setup.tokens.primeToken.address, setup.balancer.pool.address, _initreward, _starttime, _durationDays, setup.organization.avatar
What is an issue about initreward actually?

2021-04-28 12:03 UTC, BritikovKI approved these changes

2021-04-29 00:12 UTC, merged